sudo: required

services:
  - docker

install:
  - docker build -t cfnex .
  - docker run --entrypoint /bin/sh -w '/src' cfnex 'npm install'

script:
  - docker run --entrypoint /bin/sh -w '/src' cfnex 'npm test'